### ISSUE TITLE
Bug when trying to construct a PopupMenu with a Navigator

### ISSUE THREAD

**Issue by mishadynin** [flutter/engine#1145]
When I am trying to create a popup menu in my app and pass it a navigator instance (because currently PopupMenu doesn't handle null navigator), I get an assertion failure deep within Sky code:

```
I/sky     (13083): Constructing menu
I/sky     (13083): ------------------------------------------------------------------------
I/sky     (13083): Exception caught while syncing build output of Stateful GestureDetector(unkeyed; hashCode=133091970)
I/sky     (13083):   old child: null
I/sky     (13083):   new child: Listener(unkeyed; hashCode=144979143)
I/sky     (13083): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 880 pos 12: '!_debugIsBuilding' is not true.
I/sky     (13083): Stack trace:
I/sky     (13083): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/sky     (13083): #1      Component._scheduleBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:880:12)
I/sky     (13083): #2      StatefulComponent.setState (http://localhost:9888/packages/sky/src/widgets/framework.dart:952:5)
I/sky     (13083): #3      Navigator.push (http://localhost:9888/packages/sky/src/widgets/navigator.dart:162:5)
I/sky     (13083): #4      Navigator.pushState (http://localhost:9888/packages/sky/src/widgets/navigator.dart:152:5)
I/sky     (13083): #5      PopupMenu._open (http://localhost:9888/packages/sky/src/widgets/popup_menu.dart:72:15)
I/sky     (13083): #6      PopupMenu.initState (http://localhost:9888/packages/sky/src/widgets/popup_menu.dart:56:7)
I/sky     (13083): #7      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:923:9)
I/sky     (13083): #8      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #9      TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:573:13)
I/sky     (13083): #10     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #11     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1265:18)
I/sky     (13083): #12     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1449:7)
I/sky     (13083): #13     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1116:5)
I/sky     (13083): #14     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #15     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:573:13)
I/sky     (13083): #16     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #17     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #18     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:932:16)
I/sky     (13083): #19     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #20     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #21     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #22     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1265:18)
I/sky     (13083): #23     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1449:7)
I/sky     (13083): #24     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1116:5)
I/sky     (13083): #25     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #26     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #27     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:932:16)
I/sky     (13083): #28     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:467:19)
I/sky     (13083): #29     RenderObjectWrapper.syncChildren (http://localhost:9888/packages/sky/src/widgets/framework.dart:1284:18)
I/sky     (13083): #30     MultiChildRenderObjectWrapper.syncRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1449:7)
I/sky     (13083): #31     RenderObjectWrapper._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:1116:5)
I/sky     (13083): #32     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #33     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:573:13)
I/sky     (13083): #34     Inherited._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:617:16)
I/sky     (13083): #35     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #36     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #37     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:932:16)
I/sky     (13083): #38     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:467:19)
I/sky     (13083): #39     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #40     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:932:16)
I/sky     (13083): #41     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:467:19)
I/sky     (13083): #42     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #43     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #44     TagNode._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:573:13)
I/sky     (13083): #45     Inherited._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:617:16)
I/sky     (13083): #46     Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:478:13)
I/sky     (13083): #47     Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:845:16)
I/sky     (13083): #48     StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:932:16)
I/sky     (13083): #49     Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:876:5)
I/sky     (13083): #50     _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1011:19)
I/sky     (13083): #51     Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:889:7)
I/sky     (13083): #52     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1487:15)
I/sky     (13083): #53     Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
I/sky     (13083): Build stack:
I/sky     (13083):   Stateful SkyApp(unkeyed; hashCode=179188591)
I/sky     (13083):   Title(unkeyed; hashCode=1024780848)
I/sky     (13083):   Stateful Navigator(unkeyed; hashCode=328934133)
I/sky     (13083):   Stateful Focus(unkeyed; hashCode=134952907)(focusedScope=[GlobalKey 888612339]; focusedWidget=[GlobalKey 558110388])
I/sky     (13083):   Stateful SkyAppHome(unkeyed; hashCode=129010506)
I/sky     (13083):   ModalOverlay(unkeyed; hashCode=118789536)
I/sky     (13083):   Stateful GestureDetector(unkeyed; hashCode=133091970)
I/sky     (13083): Current application widget tree:
```

**Comment by Hixie** [comment]
I'm rewriting how popup menus work. I'll take this.

**Comment by Hixie** [comment]
This should be fixed now. Please reopen if not.
