### ISSUE TITLE
Exception caught while syncing children of Mimicable

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1199]
```
I/sky     ( 5034): ------------------------------------------------------------------------
I/sky     ( 5034): Exception caught while syncing children of Mimicable([GlobalKey Object(546087048)]; hashCode=832568550; mounted; gen-22; dirty; stateful})
I/sky     ( 5034):   old child: ConstrainedBox(hashCode=88170719; mounted; gen-22})
I/sky     ( 5034):   new child: SizeObserver(hashCode=425619084; not mounted; gen-125})
I/sky     ( 5034): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 1377 pos 12: '_ancestor.renderObject != null' is not true.
I/sky     ( 5034): Stack trace:
I/sky     ( 5034): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/sky     ( 5034): #1      RenderObjectWrapper.detachRenderObject (http://localhost:9888/packages/sky/src/widgets/framework.dart:1377:12)
I/sky     ( 5034): #2      Widget.syncChild (http://localhost:9888/packages/sky/src/widgets/framework.dart:466:22)
I/sky     ( 5034): #3      Component._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:870:16)
I/sky     ( 5034): #4      StatefulComponent._sync (http://localhost:9888/packages/sky/src/widgets/framework.dart:968:16)
I/sky     ( 5034): #5      Component._buildIfDirty (http://localhost:9888/packages/sky/src/widgets/framework.dart:907:5)
I/sky     ( 5034): #6      _buildDirtyComponents (http://localhost:9888/packages/sky/src/widgets/framework.dart:1050:19)
I/sky     ( 5034): #7      Component.flushBuild (http://localhost:9888/packages/sky/src/widgets/framework.dart:920:7)
I/sky     ( 5034): #8      WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/src/widgets/framework.dart:1550:15)
I/sky     ( 5034): #9      Scheduler.beginFrame (http://localhost:9888/packages/sky/src/animation/scheduler.dart:53:15)
```

**Comment by apwilson** [comment]
I'll try to reduce to a test case.

**Comment by apwilson** [comment]
I can't reproduce this issue directly.  I think this issue might go away if this issue is fixed: https://github.com/domokit/sky_engine/issues/1209

**Comment by Hixie** [comment]
Is this gone now?

**Comment by abarth** [comment]
I'm going to assume this issue was fixed by fn3.  Please re-open if that's not the case.  (The stack above doesn't exist anymore.)
