### ISSUE TITLE
Detecting just Pan events causes an exception in GestureDetector

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1320]
The following code reproduces the issue.  Touch the red box to cause the exception.

```dart
import 'package:sky/widgets.dart';

class ProblematicApp extends App {
  Widget build() {
    return new GestureDetector(
        onPanStart: () {}, onPanUpdate: (_) {}, onPanEnd: (_) {},
        child: new Container(
            decoration:
                new BoxDecoration(backgroundColor: new Color(0xFFFF0000))));
  }
}

void main() {
  runApp(new ProblematicApp());
}
```

**Comment by abarth** [comment]
Looking.

**Comment by abarth** [comment]
```
10-02 17:10:27.500   900   969 E chromium: The null object does not have a method 'addRoute'.
10-02 17:10:27.500   900   969 E chromium: 
10-02 17:10:27.500   900   969 E chromium: NoSuchMethodError: method not found: 'addRoute'
10-02 17:10:27.500   900   969 E chromium: Receiver: null
10-02 17:10:27.500   900   969 E chromium: Arguments: [0, Closure: (PointerEvent) => void from Function 'handleEvent':.]
10-02 17:10:27.500   900   969 E chromium: #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
10-02 17:10:27.500   900   969 E chromium: #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
10-02 17:10:27.500   900   969 E chromium: #2      GestureRecognizer.startTrackingPointer (http://localhost:9888/packages/sky/src/gestures/recognizer.dart:47:13)
10-02 17:10:27.500   900   969 E chromium: #3      _DragGestureRecognizer.addPointer (http://localhost:9888/packages/sky/src/gestures/drag.dart:54:5)
10-02 17:10:27.500   900   969 E chromium: #4      GestureDetectorState._handlePointerDown (http://localhost:9888/packages/sky/src/widgets/gesture_detector.dart:219:12)
10-02 17:10:27.500   900   969 E chromium: #5      RenderPointerListener.handleEvent (http://localhost:9888/packages/sky/src/rendering/proxy_box.dart:1047:27)
10-02 17:10:27.500   900   969 E chromium: #6      FlutterBinding.dispatchEvent (http://localhost:9888/packages/sky/src/rendering/binding.dart:160:20)
10-02 17:10:27.500   900   969 E chromium: #7      FlutterBinding._handlePointerEvent (http://localhost:9888/packages/sky/src/rendering/binding.dart:145:5)
10-02 17:10:27.500   900   969 E chromium: #8      FlutterBinding._handleEvent (http://localhost:9888/packages/sky/src/rendering/binding.dart:98:7)
```
