### ISSUE TITLE
Editable Paragraph throwing asserts when used

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1451]
```
10-01 17:12:22.931 I/sky     (16045): NoSuchMethodError: method not found: 'dx'
10-01 17:12:22.931 I/sky     (16045): Receiver: null
10-01 17:12:22.931 I/sky     (16045): Arguments: []
10-01 17:12:22.931 I/sky     (16045): Stack trace:
10-01 17:12:23.043 I/sky     (16045): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
10-01 17:12:23.043 I/sky     (16045): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
10-01 17:12:23.043 I/sky     (16045): #2      Offset.- (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/CustomOffset.dart:35)
10-01 17:12:23.043 I/sky     (16045): #3      RenderEditableParagraph.paint (http://localhost:9888/packages/sky/src/rendering/editable_paragraph.dart:107:46)
10-01 17:12:23.043 I/sky     (16045): #4      RenderObject._paintWithContext (http://localhost:9888/packages/sky/src/rendering/object.dart:973:7)
10-01 17:12:23.043 I/sky     (16045): #5      PaintingContext.insertChild (http://localhost:9888/packages/sky/src/rendering/object.dart:308:11)
10-01 17:12:23.043 I/sky     (16045): #6      PaintingContext.paintChild (http://localhost:9888/packages/sky/src/rendering/object.dart:127:7)
10-01 17:12:23.043 I/sky     (16045): #7      RenderProxyBox.paint (http://localhost:9888/packages/sky/src/rendering/proxy_box.dart:80:15)
10-01 17:12:23.043 I/sky     (16045): #8      RenderObject._paintWithContext (http://localhost:9888/packages/sky/src/rendering/object.dart:973:7)
10-01 17:12:23.043 I/sky     (16045): #9      PaintingContext.insertChild (http://localhost:9888/packages/sky/src/rendering/object.dart:308:11)
10-01 17:12:23.043 I/sky     (16045): #10     PaintingContext.pai
10-01 17:12:23.046 I/sky     (16045): The following RenderObject was being processed when the exception was fired:
10-01 17:12:23.046 I/sky     (16045): RenderEditableParagraph relayoutSubtreeRoot=up11
10-01 17:12:23.420 I/sky     (16045): -- EXCEPTION --
10-01 17:12:23.421 I/sky     (16045): The following exception was raised during paint():
10-01 17:12:23.447 I/sky     (16045): The null object does not have a getter 'dx'.
10-01 17:12:23.447 I/sky     (16045): 
```

**Comment by jason-simmons** [comment]
The code that instantiates EditableText needs to provide a value for the scrollOffset parameter.  If you want to support scrolling, you'll also need to update scrollOffset as the widget gets scroll gestures.

Take a look at how the Input widget uses EditableText.

**Comment by apwilson** [comment]
Okay, looking into this now.

**Comment by apwilson** [comment]
Ok, was my issue.  Closing.
