### ISSUE TITLE
Clicking button widget causes crash on Linux

### ISSUE THREAD

**Issue by nlacasse** [flutter/engine#1514]
I have a sky/flutter app with a button.  Clicking the button works fine on Android, and it used to work fine on Linux (desktop) as well.

However, the latest release of sky_engine breaks the button on Linux.  Clicking it yields:

```
[1006/163649:ERROR:dart_error.cc(16)] Unhandled exception:
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:211)
#1      _RenderInkWell._handleTap (packages/sky/src/widgets/ink_well.dart:180)
#2      TapGestureRecognizer.handlePrimaryPointer (packages/sky/src/gestures/tap.dart:27)
#3      PrimaryPointerGestureRecognizer.handleEvent (packages/sky/src/gestures/recognizer.dart:107)
#4      PointerRouter.route (packages/sky/src/gestures/pointer_router.dart:45)
#5      FlutterBinding.handleEvent (packages/sky/src/rendering/binding.dart:166)
#6      FlutterBinding.dispatchEvent (packages/sky/src/rendering/binding.dart:160)
#7      FlutterBinding._handlePointerEvent (packages/sky/src/rendering/binding.dart:145)
#8      FlutterBinding._handleEvent (packages/sky/src/rendering/binding.dart:98)
```

I'm running my app with `pub run sky_tools run_mojo` and in multiprocess mode.

**Comment by nlacasse** [comment]
cc @afandria

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
@j9brown
