### ISSUE TITLE
Dismissible animation sometimes runs when defunct.

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1548]
```dart
10-08 10:33:05.458 E/chromium(17605): [ERROR:dart_error.cc(16)] Unhandled exception:
10-08 10:33:05.458 E/chromium(17605): 'http://localhost:9888/packages/sky/src/widgets/framework.dart': Failed assertion: line 344 pos 12: '_debugLifecycleState != _StateLifecycle.defunct' is not true.
10-08 10:33:05.458 E/chromium(17605): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
10-08 10:33:05.458 E/chromium(17605): #1      State.setState (http://localhost:9888/packages/sky/src/widgets/framework.dart:344:12)
10-08 10:33:05.458 E/chromium(17605): #2      _DismissableState._startResizePerformance (http://localhost:9888/packages/sky/src/widgets/dismissable.dart:99:5)
10-08 10:33:05.458 E/chromium(17605): #3      _DismissableState._handleFadeCompleted (http://localhost:9888/packages/sky/src/widgets/dismissable.dart:76:7)
10-08 10:33:05.458 E/chromium(17605): #4      _DismissableState.initState.<anonymous closure> (http://localhost:9888/packages/sky/src/widgets/dismissable.dart:56:9)
10-08 10:33:05.458 E/chromium(17605): #5      Performance._checkStatusChanged (http://localhost:9888/packages/sky/src/animation/performance.dart:194:17)
10-08 10:33:05.458 E/chromium(17605): #6      Performance.didTick (http://localhost:9888/packages/sky/src/animation/performance.dart:221:5)
10-08 10:33:05.458 E/chromium(17605): #7      Performance._tick (http://localhost:9888/packages/sky/src/animation/performance.dart:216:5)
10-08 10:33:05.458 E/chromium(17605): #8      SimulationStepper._tick (http://localhost:9888/packages/sky/src/animation/simulation_stepper.dart:103:12)
10-08 10:33:05.458 E/chromium(17605): #9      Ticker._tick (http://localhost:9888/packages/sky/src/animation/ticker.dart:67:12)
10-08 10:33:05.458 E/chromium(17605): #10     Scheduler.beginFrame.<anonymous closure> (http://localhost:9888/packages/sky/src/animation/scheduler.dart:50:17)
```

**Comment by abarth** [comment]
@HansMuller I closing this issue assuming #1549 fixed it.

**Comment by HansMuller** [comment]
@abarth Thanks, that was the idea.
