### ISSUE TITLE
Can't bootstrap a flutter/engine checkout

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1667]
I followed the steps on https://github.com/flutter/engine/blob/master/CONTRIBUTING.md up to the point where you run `glient sync`, but then it failed:

```
________ running '/usr/bin/python src/sky/tools/dart_pub_get.py --repository-root ../.. --dart-sdk-directory ../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/packages/sky' in '/home/ianh/dev/flutter'
Error running pub get in sky/packages/updater
Resolving dependencies...
Package mojo has no versions that match >=0.0.21 <0.1.0 derived from:
- sky_updater depends on version ^0.0.21

Traceback (most recent call last):
  File "src/sky/tools/dart_pub_get.py", line 90, in <module>
    main(_repository_root, _dart_sdk_path, args.dirs_to_ignore, args.upgrade))
  File "src/sky/tools/dart_pub_get.py", line 53, in main
    pub_get(dart_sdk_path_from_root, os.path.dirname(f), upgrade)
  File "src/sky/tools/dart_pub_get.py", line 33, in pub_get
    raise e
subprocess.CalledProcessError: Command '['/home/ianh/dev/flutter/src/sky/tools/../../third_party/dart-sdk/dart-sdk/bin/pub', 'get']' returned non-zero exit status 1
Error: Command '/usr/bin/python src/sky/tools/dart_pub_get.py --repository-root ../.. --dart-sdk-directory ../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/packages/sky' returned non-zero exit status 1 in /home/ianh/dev/flutter
Hook '/usr/bin/python src/sky/tools/dart_pub_get.py --repository-root ../.. --dart-sdk-directory ../../third_party/dart-sdk/dart-sdk --dirs-to-ignore sky/packages/sky' took 11.29 secs
```

cc @jamesr @abarth @johnmccutchan

**Comment by abarth** [comment]
This appears to be caused by @Hixie having an old version of `master` in his GitHub fork.

**Comment by Hixie** [comment]
yeah. disregard.
