### ISSUE TITLE
Weird assert

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1701]
Code:

```dart
import 'dart:async';

import 'package:flutter/widgets.dart';

class ChildList extends UniqueComponent<ChildListtState> {
  List<Widget> children;
  ChildList(this.children) : super(key: new GlobalKey());
  ChildListtState createState() => new ChildListtState();
}

class ChildListtState extends State<ChildList> {
  List<Widget> _oldChildren;
  List<Widget> _children;

  void initState() {
    super.initState();
    _oldChildren = [];
    _children = config.children;
  }

  void set children(List<Widget> children) {
    setState(() {
      _oldChildren = _children;
      _children = children;
    });
  }

  Widget build(BuildContext context) {
    return new Stack([new Column(_oldChildren), new Column(_children),]);
  }
}

void main() {
  print("Started timer...");
  ChildList childList =
      new ChildList([new AspectRatio(key: new GlobalKey(), aspectRatio: 1.0)]);
  new Timer(new Duration(seconds: 1), () {
    print("Changing children...");
    childList.currentState.children = [
      new AspectRatio(key: new GlobalKey(), aspectRatio: 1.0)
    ];
  });
  runApp(childList);
}
```

Assert

```dart
10-20 13:57:13.582 I/sky     ( 6099): -- EXCEPTION --
10-20 13:57:13.586 I/sky     ( 6099): The following exception was raised during performLayout():
10-20 13:57:13.594 I/sky     ( 6099): 'http://localhost:9888/packages/flutter/src/rendering/box.dart': Failed assertion: line 393 pos 12: '(sizedByParent && debugDoingThisResize) ||
10-20 13:57:13.594 I/sky     ( 6099):            (!sizedByParent && debugDoingThisLayout)' is not true.
10-20 13:57:13.594 I/sky     ( 6099): Stack trace:
10-20 13:57:13.613 I/sky     ( 6099): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
10-20 13:57:13.613 I/sky     ( 6099): #1      RenderBox.size= (http://localhost:9888/packages/flutter/src/rendering/box.dart:393:12)
10-20 13:57:13.613 I/sky     ( 6099): #2      RenderBox.debugResetSize (http://localhost:9888/packages/flutter/src/rendering/box.dart:414:5)
10-20 13:57:13.613 I/sky     ( 6099): #3      RenderObject.layout.<anonymous closure> (http://localhost:9888/packages/flutter/src/rendering/object.dart:737:9)
10-20 13:57:13.613 I/sky     ( 6099): #4      RenderObject.layout (http://localhost:9888/packages/flutter/src/rendering/object.dart:731:14)
10-20 13:57:13.613 I/sky     ( 6099): #5      RenderFlex.performLayout (http://localhost:9888/packages/flutter/src/rendering/flex.dart:377:15)
10-20 13:57:13.613 I/sky     ( 6099): #6      RenderObject._layoutWithoutResize (http://localhost:9888/packages/flutter/src/rendering/object.dart:682:7)
10-20 13:57:13.613 I/sky     ( 6099): #7      RenderObject.flushLayout.<anonymous closure> (http://localhost:9888/packages/flutter/src/rendering/object.dart:660:18)
10-20 13:57:13.613 I/sky     ( 6099): #8      List.forEach (dart:core-patch/growable_array.dart:233)
10-20 13:57:13.613 I/sky     ( 6099): #9      RenderObject.flushLayout (http://localhost:9888/packages/flutter/src/rendering/object.dart:658:82)
10-20 13:57:13.613 I/sky     ( 6099): #10     FlutterBinding.beginFrame (http://localhost:9888/packages/flutter/src/rendering/binding.dart:166:18)
10-20 13:57:13.613 I/sky     ( 6099): #11     WidgetFlutterBinding.beginFrame (http://localhost:9888/packages/flutter/src/widgets/binding.dart:41:21)
10-20 13:57:13.613 I/sky     ( 6099): #12     Scheduler.beginFrame (http://localhost:9888/packages/flutter/src/animation/scheduler.dart:55:15)
10-20 13:57:13.616 I/sky     ( 6099): The following RenderObject was being processed when the exception was fired:
10-20 13:57:13.616 I/sky     ( 6099): RenderFlex NEEDS-LAYOUT

```

**Comment by Hixie** [comment]
fixed
