### ISSUE TITLE
Hard to debug exception during paint()

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/engine#219]
I added some code to a RenderObject which caused it to throw an exception during paint().

I got unending spew of:
```
I/sky     ( 1705): Exception raised during _updatePaintingCanvas:
I/sky     ( 1705): 'http://localhost:9888/packages/sky/rendering/object.dart': Failed assertion: line 384 pos 12: '!_debugDoingThisPaint' is not true.
I/sky     ( 1705): Context:
I/sky     ( 1705): RenderView
I/sky     ( 1705):   parentData: null
I/sky     ( 1705):   constraints: null
I/sky     ( 1705):   child: RenderStack
I/sky     ( 1705):     parentData: <none>
I/sky     ( 1705):     constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     ( 1705):     size: Size(360.0, 592.0)
I/sky     ( 1705):     child 1: RenderTransform
I/sky     ( 1705):       parentData: position=Point(0.0, 0.0); top=null; right=null; bottom=null, left=null
I/sky     ( 1705):       constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     ( 1705):       size: Size(360.0, 592.0)
I/sky     ( 1705):       transform matrix:
I/sky     ( 1705):         [0] 1.0,0.0,0.0,0.0
I/sky     ( 1705):         [1] 0.0,1.0,0.0,0.0
I/sky     ( 1705):         [2] 0.0,0.0,1.0,0.0
I/sky     ( 1705):         [3] 0.0,0.0,0.0,1.0
I/sky     ( 1705):       child: RenderOpacity
I/sky     ( 1705):         parentData: position=Point(0.0, 0.0)
I/sky     ( 1705):         constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     ( 1705):         size: Size(360.0, 592.0)
I/sky     ( 1705):         child: SpriteBox
I/sky     ( 1705):           parentData: position=Point(0.0, 0.0)
I/sky     ( 1705):           constraints: BoxConstraints(360.0<=w<360.0
E/chromium( 1705): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium( 1705): 'http://localhost:9888/packages/sky/rendering/object.dart': Failed assertion: line 384 pos 12: '!_debugDoingThisPaint' is not true.
E/chromium( 1705): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium( 1705): #1      RenderObject._paintOnCanvas (http://localhost:9888/packages/sky/rendering/object.dart:384:12)
E/chromium( 1705): #2      RenderObject._updatePaintingCanvas (http://localhost:9888/packages/sky/rendering/object.dart:363:7)
E/chromium( 1705): #3      RenderObject.flushPaint (http://localhost:9888/packages/sky/rendering/object.dart:347:16)
E/chromium( 1705): #4      SkyBinding._beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:74:18)
E/chromium( 1705): #5      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium( 1705): [ERROR:dart_error.cc(28)] #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium( 1705): #1      RenderObject._paintOnCanvas (http://localhost:9888/packages/sky/rendering/object.dart:384:12)
E/chromium( 1705): #2      RenderObject._updatePaintingCanvas (http://localhost:9888/packages/sky/rendering/object.dart:363:7)
E/chromium( 1705): #3      RenderObject.flushPaint (http://localhost:9888/packages/sky/rendering/object.dart:347:16)
E/chromium( 1705): #4      SkyBinding._beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:74:18)
E/chromium( 1705): #5      _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium( 1705): 
```

Which didn't actually show me my exception!

I tried debugging with:
```
diff --git a/sky/sdk/lib/rendering/object.dart b/sky/sdk/lib/rendering/object.dart
index b0a1b88..cda816d 100644
--- a/sky/sdk/lib/rendering/object.dart
+++ b/sky/sdk/lib/rendering/object.dart
@@ -394,7 +394,11 @@ abstract class RenderObject extends AbstractNode implements HitTestTarget {
       }
       return true;
     });
-    paint(canvas, offset);
+    try {
+      paint(canvas, offset);
+    } catch(e) {
+      print("Exception during paint(): " + e);
+    }
     assert(() {
       if (debugPaintBoundsEnabled)
         canvas.restore();
```

But that didn't seem to catch the exception?  Eventually I moved that try/catch code into my paint() function to debug there.  But this should have been much easier.

Maybe there is a way to get the app to stop on the first exception?  Or we should fix the debug paint code to actually print the exception that caused the paint to fail instad of a constant stream of some debug variable not having been cleared?  It doesn't seem like the system can recover from this state once it hits it once.

@Hixie

**Comment by Hixie** [comment]
Can you give an example bug that would show this?

**Comment by Hixie** [comment]
This may be solved already, but it's not clear to me. Eric, can you elaborate on how you trigger this?

**Comment by eseidel** [comment]
I beleive I just modified any old renderobject and added an exception.  Try modifying RenderFlex.paint to throw and seeing if it barfs in a useful manner.

**Comment by abarth** [comment]
We've improved this a bunch.
