### ISSUE TITLE
mojom callbacks with no arguments fail to decode in Dart

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#39]
_From @eseidelGoogle on June 30, 2015 1:19_

mojom callbacks with no arguments fail to decode in Dart

Example:
```
interface MediaPlayer {
  prepare() => ();
}

E/chromium( 3708): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium( 3708): Uncaught Error: Expected a message with a valid request Id.
E/chromium( 3708): Stack Trace:
E/chromium( 3708): #0      MediaPlayerProxyImpl.handleResponse (http://localhost:9888/packages/mojom/media/media.mojom.dart:481:11)
E/chromium( 3708): #1      Proxy.handleRead (http://localhost:9888/packages/mojo/src/proxy.dart:50:5)
E/chromium( 3708): #2      MojoEventStreamListener.listen.<anonymous closure> (http://localhost:9888/packages/mojo/src/event_stream.dart:203:9)
E/chromium( 3708): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
E/chromium( 3708): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
E/chromium( 3708): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
E/chromium( 3708): #6      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
E/chromium( 3708): #7      _StreamController._add (dart:async/stream_controller.dart:567)
E/chromium( 3708): #8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1104)
E/chromium( 3708): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
E/chromium( 3708): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
E/chromium( 3708): #11     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:695)
E/chromium( 3708): #12     _StreamController._add (dart:async/stream_controller.dart:567)
E/chromium( 3708): #13     _StreamController.add (dart:async/stream_controller.dart:513)
E/chromium( 3708): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
E/chromium( 3708): 
E/chromium( 3708): #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium( 3708): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium( 3708): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
E/chromium( 3708): [ERROR:dart_error.cc(28)] #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
E/chromium( 3708): #1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
E/chromium( 3708): #2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
```

@abarth says the bug is in mojo/public/tools/bindings/generators/java_templates/interface_definition.tmpl

_Copied from original issue: domokit/mojo#282_

**Comment by Hixie** [comment]
_From @abarth on June 30, 2015 1:51_

I think the problem is on the Java encoder side.  We don't seem to be encoding the bit in the flag that says this message is a response.

**Comment by abarth** [comment]
This was fixed in mojo land.
