### ISSUE TITLE
Dismissable sometimes throws exceptions when dismissing

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#593]
Call Stack:
```
08-13 10:37:27.506 E/chromium(18432): [ERROR:dart_error.cc(19)] Unhandled exception:
08-13 10:37:27.506 E/chromium(18432): 'http://localhost:9888/packages/sky/rendering/object.dart': Failed assertion: line 585 pos 14: '_debugUltimatePreviousSiblingOf(before, equals: _firstChild)' is not true.
08-13 10:37:27.506 E/chromium(18432): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
08-13 10:37:27.506 E/chromium(18432): #1      RenderBox&ContainerRenderObjectMixin._addToChildList (http://localhost:9888/packages/sky/rendering/object.dart:585:14)
08-13 10:37:27.506 E/chromium(18432): #2      RenderBox&ContainerRenderObjectMixin.add (http://localhost:9888/packages/sky/rendering/object.dart:615:5)
08-13 10:37:27.506 E/chromium(18432): #3      MultiChildRenderObjectWrapper.insertChildRoot (http://localhost:9888/packages/sky/widgets/framework.dart:1014:10)
08-13 10:37:27.506 E/chromium(18432): #4      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/widgets/framework.dart:878:19)
08-13 10:37:27.506 E/chromium(18432): #5      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
08-13 10:37:27.506 E/chromium(18432): #6      StatefulComponent.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:746:27)
08-13 10:37:27.506 E/chromium(18432): #7      Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:651:14)
08-13 10:37:27.506 E/chromium(18432): #8      StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:730:16)
08-13 10:37:27.506 E/chromium(18432): #9      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
08-13 10:37:27.506 E/chromium(18432): #10     StatefulComponent.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:746:27)
08-13 10:37:27.506 E/chromium(18432): #11     Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:651:14)
08-13 10:37:27.506 E/chromium(18432): #12     StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:730:16)
08-13 10:37:27.506 E/chromium(18432): #13     Component._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:666:5)
08-13 10:37:27.506 E/chromium(18432): #14     StatefulComponent._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:700:24)
08-13 10:37:27.506 E/chromium(18432): #15     _buildDirtyComponents (http://localhost:9888/packages/sky/widgets/framework.dart:805:19)
08-13 10:37:27.506 E/chromium(18432): #16     Component.flushBuild (http://localhost:9888/packages/sky/widgets/framework.dart:679:7)
08-13 10:37:27.506 E/chromium(18432): #17     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1222:15)
08-13 10:37:27.506 E/chromium(18432): #18     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
08-13 10:37:27.551 E/chromium(18432): [ERROR:dart_error.cc(28)] #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
08-13 10:37:27.551 E/chromium(18432): #1      RenderBox&ContainerRenderObjectMixin._addToChildList (http://localhost:9888/packages/sky/rendering/object.dart:585:14)
08-13 10:37:27.551 E/chromium(18432): #2      RenderBox&ContainerRenderObjectMixin.add (http://localhost:9888/packages/sky/rendering/object.dart:615:5)
08-13 10:37:27.551 E/chromium(18432): #3      MultiChildRenderObjectWrapper.insertChildRoot (http://localhost:9888/packages/sky/widgets/framework.dart:1014:10)
08-13 10:37:27.551 E/chromium(18432): #4      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/widgets/framework.dart:878:19)
08-13 10:37:27.551 E/chromium(18432): #5      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
08-13 10:37:27.551 E/chromium(18432): #6      StatefulComponent.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:746:27)
08-13 10:37:27.551 E/chromium(18432): #7      Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:651:14)
08-13 10:37:27.551 E/chromium(18432): #8      StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:730:16)
08-13 10:37:27.551 E/chromium(18432): #9      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:337:13)
08-13 10:37:27.551 E/chromium(18432): #10     StatefulComponent.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:746:27)
08-13 10:37:27.551 E/chromium(18432): #11     Component._sync (http://localhost:9888/packages/sky/widgets/framework.dart:651:14)
08-13 10:37:27.551 E/chromium(18432): #12     StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:730:16)
08-13 10:37:27.551 E/chromium(18432): #13     Component._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:666:5)
08-13 10:37:27.551 E/chromium(18432): #14     StatefulComponent._buildIfDirty (http://localhost:9888/packages/sky/widgets/framework.dart:700:24)
08-13 10:37:27.551 E/chromium(18432): #15     _buildDirtyComponents (http://localhost:9888/packages/sky/widgets/framework.dart:805:19)
08-13 10:37:27.551 E/chromium(18432): #16     Component.flushBuild (http://localhost:9888/packages/sky/widgets/framework.dart:679:7)
08-13 10:37:27.551 E/chromium(18432): #17     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1222:15)
08-13 10:37:27.551 E/chromium(18432): #18     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
08-13 10:37:27.551 E/chromium(18432): 
08-13 10:37:27.569 E/chromium(18432): [ERROR:dart_error.cc(19)] Unhandled exception:
08-13 10:37:27.569 E/chromium(18432): 'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 670 pos 12: '!_isBuilding' is not true.
08-13 10:37:27.569 E/chromium(18432): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
08-13 10:37:27.569 E/chromium(18432): #1      Component._scheduleBuild (http://localhost:9888/packages/sky/widgets/framework.dart:670:12)
08-13 10:37:27.569 E/chromium(18432): #2      StatefulComponent.setState (http://localhost:9888/packages/sky/widgets/framework.dart:752:5)
08-13 10:37:27.569 E/chromium(18432): #3      AnimatedComponent._performanceChanged (http://localhost:9888/packages/sky/widgets/animated_component.dart:17:5)
08-13 10:37:27.569 E/chromium(18432): #4      AnimationPerformance._notifyListeners (http://localhost:9888/packages/sky/animation/animation_performance.dart:135:15)
08-13 10:37:27.569 E/chromium(18432): #5      AnimationPerformance._tick (http://localhost:9888/packages/sky/animation/animation_performance.dart:178:5)
08-13 10:37:27.569 E/chromium(18432): #6      Timeline._tick (http://localhost:9888/packages/sky/animation/timeline.dart:77:12)
08-13 10:37:27.569 E/chromium(18432): #7      AnimatedSimulation._tick (http://localhost:9888/packages/sky/animation/animated_simulation.dart:113:12)
08-13 10:37:27.569 E/chromium(18432): #8      Ticker._tick (http://localhost:9888/packages/sky/animation/animated_simulation.dart:52:12)
08-13 10:37:27.569 E/chromium(18432): #9      _beginFrame.<anonymous closure> (http://localhost:9888/packages/sky/base/scheduler.dart:26:13)
08-13 10:37:27.569 E/chromium(18432): #10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
08-13 10:37:27.569 E/chromium(18432): #11     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:25:13)
08-13 10:37:27.575 E/chromium(18432): [ERROR:dart_error.cc(28)] #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
08-13 10:37:27.575 E/chromium(18432): #1      Component._scheduleBuild (http://localhost:9888/packages/sky/widgets/framework.dart:670:12)
08-13 10:37:27.575 E/chromium(18432): #2      StatefulComponent.setState (http://localhost:9888/packages/sky/widgets/framework.dart:752:5)
08-13 10:37:27.575 E/chromium(18432): #3      AnimatedComponent._performanceChanged (http://localhost:9888/packages/sky/widgets/animated_component.dart:17:5)
08-13 10:37:27.575 E/chromium(18432): #4      AnimationPerformance._notifyListeners (http://localhost:9888/packages/sky/animation/animation_performance.dart:135:15)
08-13 10:37:27.575 E/chromium(18432): #5      AnimationPerformance._tick (http://localhost:9888/packages/sky/animation/animation_performance.dart:178:5)
08-13 10:37:27.575 E/chromium(18432): #6      Timeline._tick (http://localhost:9888/packages/sky/animation/timeline.dart:77:12)
08-13 10:37:27.575 E/chromium(18432): #7      AnimatedSimulation._tick (http://localhost:9888/packages/sky/animation/animated_simulation.dart:113:12)
08-13 10:37:27.575 E/chromium(18432): #8      Ticker._tick (http://localhost:9888/packages/sky/animation/animated_simulation.dart:52:12)
08-13 10:37:27.575 E/chromium(18432): #9      _beginFrame.<anonymous closure> (http://localhost:9888/packages/sky/base/scheduler.dart:26:13)
08-13 10:37:27.575 E/chromium(18432): #10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
08-13 10:37:27.575 E/chromium(18432): #11     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:25:13)
```

**Comment by Hixie** [comment]
Does this still happen?

**Comment by Hixie** [comment]
@apwilson Please reopen if this still happens.
