### ISSUE TITLE
Drawer.initState() fails

### ISSUE THREAD

**Issue by HansMuller** [flutter/engine#715]
Launch the stocks demo and then immediately tap the "show drawer" icon (toolbar left).
```
E/chromium(16844): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(16844): 'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 691 pos 12: '!_isBuilding' is not true.
E/chromium(16844): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(16844): #1      Component._scheduleBuild (http://localhost:9888/packages/sky/widgets/framework.dart:691:12)
E/chromium(16844): #2      StatefulComponent.setState (http://localhost:9888/packages/sky/widgets/framework.dart:775:5)
E/chromium(16844): #3      Navigator.push (http://localhost:9888/packages/sky/widgets/navigator.dart:179:5)
E/chromium(16844): #4      Navigator.pushState (http://localhost:9888/packages/sky/widgets/navigator.dart:169:5)
E/chromium(16844): #5      Drawer.initState (http://localhost:9888/packages/sky/widgets/drawer.dart:71:17)
E/chromium(16844): #6      StatefulComponent._sync (http://localhost:9888/packages/sky/widgets/framework.dart:746:7)
E/chromium(16844): #7      Widget.syncChild (http://localhost:9888/packages/sky/widgets/framework.dart:359:13)
E/chromium(16844): #8      Scaffold.syncRenderObject (http://localhost:9888/packages/sky/widgets/scaffold.dart:231:22)
E/chromium(16844): #9      RenderObjectWrapper._sync (http://localhost:9888/packages/sky/widgets/framework.dart:923:5)
```
This occurs because Drawer.initState() is called while the Navigator is building and Drawer.initState() implicitly does Navigator.scheduleBuild():
```
    if (navigator != null) {
      navigator.pushState(this, (_) => _performance.reverse()); // ... navigator.scheduleBuild()
    }
```
This statement enables the back button to DTRT.

It's happening at initState() time because the Drawer is being created with its open animation started. Drawer appears to mostly ignore its showing property. For example creating a Drawer with showing:false doesn't appear to work. The stocks demo cooperates by only creating the Drawer when it's time to show it.

The bug can be worked around by restoring the '\\\ooooo/////' workaround removed by https://github.com/domokit/sky_engine/pull/592.

**Comment by HansMuller** [comment]
If the navigator pushState() call occured in the event handler that triggers showing the Drawer, we'd avoid this problem.  Perhaps we need Scaffold.showDrawer().
