### ISSUE TITLE
Stack of Positioned Stacks with Positioned Widgets Fails to Render

### ISSUE THREAD

**Issue by afandria** [flutter/engine#732]
Here is my example code. We have a Stack of Positioned Stacks with Positioned Text widgets.

```
import 'package:sky/widgets/basic.dart';

class HelloWorldApp extends App {

  Widget build() {
    List<Widget> positionedStacks = new List<Widget>();
    for (int i = 0; i < 4; i++) {
      List<Widget> widgets = new List<Widget>();
      for (int j = 0; j < 5; j++) {
        widgets.add(new Positioned(
          // If left/right/top/down are assigned to a non-null value, the error occurs.
          left: j * 40.0, // If this line is deleted, there is no error (and all text overlaps).
          child: new Text('A${j}')
        ));
      }
      positionedStacks.add(new Positioned(
        top: (i+1) * 30.0,
        child: new Stack(widgets)
      ));
    }

    return new Stack(positionedStacks);
  }
}

void main() {
  runApp(new HelloWorldApp());
}
```

Briefly, the error is in rendering/stack.dart is:
__'http://localhost:9888/packages/sky/rendering/stack.dart': Failed assertion: line 146 pos 12: 'size.width == constraints.constrainWidth(width)' is not true.__

adb logcat follows:

```
I/sky     (16621): 'http://localhost:9888/packages/sky/rendering/stack.dart': Failed assertion: line 146 pos 12: 'size.width == constraints.constrainWidth(width)' is not true.
I/sky     (16621): Context:
I/sky     (16621): RenderView NEEDS-LAYOUT
I/sky     (16621):   parentData: null
I/sky     (16621):   constraints: null
I/sky     (16621):   child: RenderStack NEEDS-LAYOUT
I/sky     (16621):     parentData: <none>
I/sky     (16621):     constraints: BoxConstraints(360.0<=w<360.0, 592.0<=h<592.0)
I/sky     (16621):     size: Size(360.0, 592.0)
I/sky     (16621):     child 1: RenderStack relayoutSubtreeRoot=up1 NEEDS-LAYOUT
I/sky     (16621):       parentData: position=Point(0.0, 0.0); top=30.0; right=null; bottom=null, left=null
I/sky     (16621):       constraints: BoxConstraints(0.0<=w<360.0, 0.0<=h<562.0)
I/sky     (16621):       size: Size(360.0, 562.0)
I/sky     (16621):       child 1: RenderParagraph NEEDS-LAYOUT
I/sky     (16621):         parentData: position=Point(0.0, 0.0); top=null; right=null; bottom=null, left=0.0
I/sky     (16621):         constraints: null
I/sky     (16621):         size: Size(0.0, 0.0)
I/sky     (16621):         text:
I/sky     (16621):           PlainTextSpan: "A0"
I/sky     (16621):       child 2: RenderParagraph NEEDS-LAYOUT
I/sky     (16621):         parentData: position=Point(0.0, 0.0); top=null; right=null; bottom=null, left=40.0
E/chromium(16621): [ERROR:dart_error.cc(19)] Unhandled exception:
E/chromium(16621): 'http://localhost:9888/packages/sky/rendering/stack.dart': Failed assertion: line 146 pos 12: 'size.width == constraints.constrainWidth(width)' is not true.
E/chromium(16621): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(16621): #1      RenderStack.performLayout (http://localhost:9888/packages/sky/rendering/stack.dart:146:12)
E/chromium(16621): #2      RenderObject.layout (http://localhost:9888/packages/sky/rendering/object.dart:343:5)
E/chromium(16621): #3      RenderStack.performLayout (http://localhost:9888/packages/sky/rendering/stack.dart:173:15)
E/chromium(16621): #4      RenderObject.layout (http://localhost:9888/packages/sky/rendering/object.dart:343:5)
E/chromium(16621): #5      RenderView.performLayout (http://localhost:9888/packages/sky/rendering/view.dart:65:13)
E/chromium(16621): #6      RenderObject.layoutWithoutResize (http://localhost:9888/packages/sky/rendering/object.dart:296:7)
E/chromium(16621): #7      RenderObject.flushLayout.<anonymous closure> (http://localhost:9888/packages/sky/rendering/object.dart:275:16)
E/chromium(16621): #8      List.forEach (dart:core-patch/growable_array.dart:234)
E/chromium(16621): #9      RenderObject.flushLayout (http://localhost:9888/packages/sky/rendering/object.dart:273:54)
E/chromium(16621): #10     SkyBinding.beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:74:18)
E/chromium(16621): #11     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1258:21)
E/chromium(16621): #12     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium(16621): [ERROR:dart_error.cc(28)] #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/chromium(16621): #1      RenderStack.performLayout (http://localhost:9888/packages/sky/rendering/stack.dart:146:12)
E/chromium(16621): #2      RenderObject.layout (http://localhost:9888/packages/sky/rendering/object.dart:343:5)
E/chromium(16621): #3      RenderStack.performLayout (http://localhost:9888/packages/sky/rendering/stack.dart:173:15)
E/chromium(16621): #4      RenderObject.layout (http://localhost:9888/packages/sky/rendering/object.dart:343:5)
E/chromium(16621): #5      RenderView.performLayout (http://localhost:9888/packages/sky/rendering/view.dart:65:13)
E/chromium(16621): #6      RenderObject.layoutWithoutResize (http://localhost:9888/packages/sky/rendering/object.dart:296:7)
E/chromium(16621): #7      RenderObject.flushLayout.<anonymous closure> (http://localhost:9888/packages/sky/rendering/object.dart:275:16)
E/chromium(16621): #8      List.forEach (dart:core-patch/growable_array.dart:234)
E/chromium(16621): #9      RenderObject.flushLayout (http://localhost:9888/packages/sky/rendering/object.dart:273:54)
E/chromium(16621): #10     SkyBinding.beginFrame (http://localhost:9888/packages/sky/rendering/sky_binding.dart:74:18)
E/chromium(16621): #11     WidgetSkyBinding.beginFrame (http://localhost:9888/packages/sky/widgets/framework.dart:1258:21)
E/chromium(16621): #12     _beginFrame (http://localhost:9888/packages/sky/base/scheduler.dart:30:13)
E/chromium(16621): 
```

======================================

For comparison, this alternative is similar in structure, but does work:

```
  // This code here works, but with a Stack of Positioned Flexes with Texts inside.
  Widget build() {
    List<Widget> positionedStacks = new List<Widget>();
    for (int i = 0; i < 4; i++) {
      List<Widget> widgets = new List<Widget>();
      for (int j = 0; j < 5; j++) {
        widgets.add(new Text('A${j}'));
      }
      positionedStacks.add(new Positioned(
        top: (i+1) * 30.0,
        child: new Flex(widgets)
      ));
    }

    return new Stack(positionedStacks);
  }
```

![screenshot_2015-08-20-18-07-31](https://cloud.githubusercontent.com/assets/2432033/9399313/5a7e05dc-4767-11e5-9589-6669b506192c.png)

(You can also use a Flex of Flexible Text Widgets, and that will render properly too.)

**Comment by Hixie** [comment]
Is the issue that the stacks in the outer stack end of being 0x0 because they don't have anything setting their dimensions, or something?

**Comment by abarth** [comment]
The issue is that the child stacks don't know how big they're supposed to be.  They're given unlimited space to work with and no reference points for how big they should be.  By default, they try to be as big as possible, but that doesn't work well in this case because that makes them infinitely big.

It seems like what you probably want is something like the following:

```patch
@@ -15,7 +15,12 @@ class HelloWorldApp extends App {
       }
       positionedStacks.add(new Positioned(
         top: (i+1) * 30.0,
-        child: new Stack(widgets)
+        left: 0.0,
+        right: 0.0,
+        child: new Container(
+          height: 30.0,
+          child: new Stack(widgets)
+        )
       ));
     }
 
```

That makes the child stacks the same width as the parent stack and gives each one a height of 30.0.

We used to size positioned children of stacks to the size of the stack, but that cause problems for folks who wanted to position children that were bigger than the stack itself and have the stack clip those children.

**Comment by afandria** [comment]
Yes, that works for me. For most use-cases, wrapping up the internal Stacks with a sized Container shouldn't be a problem. I think it's worthwhile to document that a Stack's children will generally need to have known size to avoid this issue.

**Comment by abarth** [comment]
This is now documented in the API docs for Stack.
